# Hexo Auto Deploy Action

name: Deploy Hexo Blog

# When Push Source File to Branch "master" run this Action
on:
  push:
    branches: master


jobs:
  # job build (friendly name "build on ubuntu-latest" with theme yun)
  build:
    name: Build on ${{ matrix.os }} with theme yun
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set NodeJS Environment
        uses: actions/setup-node@v2

      - name: Set Hexo Enviroment
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          npm i -g hexo-cli
          npm i
          npm install hexo-render-pug hexo-renderer-stylus 
        # Install Hexo and necessary render for theme yun

      - name: Get Repo & Download Latest Themes
        run: |
          git clone https://github.com/EdenJohnson2006/BlogBackup.git gitblog
          cd gitblog
          git clone -b master https://github.com/YunYouJun/hexo-theme-yun themes/yun
          
      - name: Generate Hexo File
        run:  /home/runner/.npm-global/bin/hexo g
        
      - name: Deploy With Github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.HEXO_DEPLOY_PRI }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          REPOSITORY_NAME: EdenJohnson2006/EdenJohnson2006.github.io
          CLEAN: true # Automatically remove deleted files from the deploy branch