# Hexo Auto Deploy Action

name: Deploy Hexo Blog

# When Push Source File to Branch "master" run this Action
on:
  push:
    branches: master


jobs:
  # job build (friendly name "build on ubuntu-latest" with theme yun)
  build:
    name: Build on ${{ matrix.os }} with theme yun
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]

    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set NodeJS Environment
        uses: actions/setup-node@v2

      - name: Set Hexo Enviroment
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          npm i -g hexo-cli
          npm i
          npm install hexo-render-pug hexo-renderer-stylus 
        # Install Hexo and necessary render for theme yun

      - name: Get Repo & Download Latest Themes
        run: |
          git clone https://github.com/EdenJohnson2006/BlogBackup.git gitblog
          cd gitblog
          git clone -b master https://github.com/YunYouJun/hexo-theme-yun themes/yun
          
      - name: Generate Hexo File
        run:  /home/runner/.npm-global/bin/hexo g
        
      - name: Deploy With Git
        env: 
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          git config --global user.email "ayok_ayok@outlook.com"
          git config --global user.name "EdenJohnson2006"
          cd public
          git init
          git add .
          git commit -m "test deploy"
          git branch -M master
          git remote add origin https://"$HEXO_DEPLOY_PRI"@github.com/EdenJohnson2006/EdenJohnson2006.github.io.git
          git push -u origin master
          echo "Done!"
